// services/agents/base.ts
// BaseAgent abstract class — all 14 specialized agents extend this

import type {
  AgentType,
  AgentOutputPayload,
  ExtractedFactPayload,
  RiskFlagPayload,
  AgentRecommendationPayload,
  RiskCategory,
  RiskSeverity,
} from '@/types'
import { db } from '@/lib/db'

export interface AgentInput {
  siteId: string
  userId?: string
  attachmentId?: string
  options?: Record<string, unknown>
}

export abstract class BaseAgent {
  abstract readonly agentType: AgentType
  abstract readonly displayName: string

  /** Subclasses implement their domain logic here */
  protected abstract execute(
    input: AgentInput,
    siteData: Record<string, unknown>,
  ): Promise<AgentOutputPayload>

  /** Public entry-point — creates AgentRun record, calls execute(), persists output */
  async run(input: AgentInput): Promise<string> {
    const startMs = Date.now()

    const run = await db.agentRun.create({
      data: {
        siteId:      input.siteId,
        attachmentId: input.attachmentId ?? null,
        agentType:   this.agentType as any,
        status:      'RUNNING',
        triggeredById: input.userId ?? null,
        startedAt:   new Date(),
      },
    })

    try {
      const siteData = await this.fetchSiteData(input.siteId)
      const output   = await this.execute(input, siteData)

      const factCount = await this.persistFacts(input.siteId, run.id, output.extractedFacts)
      const riskCount = await this.persistRisks(input.siteId, run.id, output.riskFlags)
      await this.persistRecommendations(run.id, output.recommendations)

      await db.agentRun.update({
        where: { id: run.id },
        data: {
          status:         'COMPLETED',
          outputPayload:  output as any,
          summary:        output.summary,
          confidenceScore: output.confidence,
          factsExtracted:  factCount,
          risksDetected:   riskCount,
          completedAt:     new Date(),
          durationMs:      Date.now() - startMs,
        },
      })

      if (output.riskFlags.some(r => r.severity === 'CRITICAL')) {
        await db.site.update({
          where: { id: input.siteId },
          data: { updatedAt: new Date() },
        })
      }

      return run.id
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      await db.agentRun.update({
        where: { id: run.id },
        data: { status: 'FAILED', error: msg, completedAt: new Date() },
      })
      throw err
    }
  }

  // ── Data fetcher ────────────────────────────────────────────────────────
  protected async fetchSiteData(siteId: string): Promise<Record<string, unknown>> {
    const site = await db.site.findUniqueOrThrow({
      where: { id: siteId },
      include: {
        utilities:            true,
        generators:           true,
        upsSystems:           true,
        coolingSystems:       true,
        networkProfiles:      { include: { fiberRoutes: true } },
        securityProfile:      true,
        complianceProfile:    true,
        environmentalProfile: true,
        capitalPlan:          true,
        financialModels:      true,
        jurisdictionProfile:  true,
        expansionPlans:       true,
        buildings:            true,
        contacts:             true,
        riskFlags:            { where: { isResolved: false } },
        attachments:          true,
        scorecard:            true,
      },
    })
    return site as unknown as Record<string, unknown>
  }

  // ── Persistence helpers ──────────────────────────────────────────────────
  private async persistFacts(
    siteId: string,
    agentRunId: string,
    facts: ExtractedFactPayload[],
  ): Promise<number> {
    if (!facts.length) return 0
    await db.extractedFact.createMany({
      data: facts.map(f => ({
        siteId,
        agentRunId,
        fieldPath:       f.fieldPath,
        fieldLabel:      f.fieldLabel,
        extractedValue:  String(f.value),
        confidence:      f.confidence,
        isInferred:      f.isInferred,
        evidenceSnippet: f.evidence ?? null,
        reviewStatus:    'PENDING',
      })),
    })
    return facts.length
  }

  private async persistRisks(
    siteId: string,
    agentRunId: string,
    risks: RiskFlagPayload[],
  ): Promise<number> {
    if (!risks.length) return 0
    await db.riskFlag.createMany({
      data: risks.map(r => ({
        siteId,
        agentRunId,
        category:       r.category as any,
        severity:       r.severity as any,
        title:          r.title,
        description:    r.description,
        recommendation: r.recommendation ?? null,
        isAutoGenerated: true,
      })),
    })
    return risks.length
  }

  private async persistRecommendations(
    agentRunId: string,
    recs: AgentRecommendationPayload[],
  ): Promise<void> {
    if (!recs.length) return
    await db.agentRecommendation.createMany({
      data: recs.map(r => ({
        agentRunId,
        category:       r.category,
        recommendation: r.recommendation,
        confidence:     r.confidence,
        evidence:       r.evidence ?? null,
        isInferred:     false,
        reviewStatus:   'PENDING',
      })),
    })
  }

  // ── Factory helpers for subclasses ───────────────────────────────────────
  protected fact(
    fieldPath: string,
    fieldLabel: string,
    value: string | number | boolean,
    confidence: number,
    evidence?: string,
    isInferred = false,
  ): ExtractedFactPayload {
    return { fieldPath, fieldLabel, value: String(value), confidence, isInferred, evidence }
  }

  protected risk(
    category: RiskCategory,
    severity: RiskSeverity,
    title: string,
    description: string,
    recommendation?: string,
  ): RiskFlagPayload {
    return { category, severity, title, description, recommendation }
  }

  protected rec(
    category: string,
    recommendation: string,
    confidence: number,
    evidence?: string,
  ): AgentRecommendationPayload {
    return { category, recommendation, confidence, evidence }
  }
}
