// types/index.ts — All shared TypeScript types for UnyKorn Data Center OS
// Mirrors the Prisma schema with additional UI/service types

export type UserRole =
  | 'ADMIN'
  | 'ANALYST'
  | 'ENGINEERING'
  | 'POWER_ENGINEER'
  | 'NETWORK_ENGINEER'
  | 'COMPLIANCE'
  | 'FINANCE'
  | 'EXECUTIVE_REVIEWER'
  | 'EXTERNAL_PARTNER'
  | 'AI_AGENT_SUPERVISOR'

export type SiteStatus =
  | 'INTAKE'
  | 'SCREENING'
  | 'IN_REVIEW'
  | 'SHORTLISTED'
  | 'IN_DILIGENCE'
  | 'APPROVED'
  | 'REJECTED'
  | 'WATCHLIST'
  | 'ARCHIVED'

export type SiteStage =
  | 'SOURCING'
  | 'QUALIFICATION'
  | 'INITIAL_REVIEW'
  | 'TECHNICAL_REVIEW'
  | 'FINANCIAL_REVIEW'
  | 'COMPLIANCE_REVIEW'
  | 'EXECUTIVE_REVIEW'
  | 'APPROVED'
  | 'REJECTED'

export type SiteType =
  | 'RETROFIT'
  | 'GREENFIELD'
  | 'POWERED_SHELL'
  | 'OPERATING_FACILITY'
  | 'LAND_ONLY'
  | 'CAMPUS_EXPANSION'
  | 'CARRIER_HOTEL'
  | 'INDUSTRIAL'

export type SiteRecommendation =
  | 'REJECT'
  | 'WATCHLIST'
  | 'STANDARD_FIT'
  | 'STRATEGIC_FIT'
  | 'FLAGSHIP_FIT'

export type RiskSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO'
export type RiskCategory =
  | 'POWER_UTILITY'
  | 'COOLING_THERMAL'
  | 'NETWORK_CONNECTIVITY'
  | 'STRUCTURAL'
  | 'ENVIRONMENTAL_CLIMATE'
  | 'COMPLIANCE_REGULATORY'
  | 'COMMERCIAL_FINANCIAL'
  | 'OPERATIONAL'
  | 'JURISDICTIONAL'
  | 'LEASE_OWNERSHIP'
  | 'DATA_QUALITY'
  | 'SECURITY'

export type AgentType =
  | 'INTAKE'
  | 'DOCUMENT_EXTRACTION'
  | 'VALIDATION'
  | 'POWER_UTILITY'
  | 'COOLING_AI_READINESS'
  | 'NETWORK'
  | 'COMPLIANCE'
  | 'RISK'
  | 'FINANCIAL_MODELING'
  | 'SUMMARY'
  | 'WORKFLOW_ORCHESTRATOR'
  | 'APPROVAL'
  | 'KNOWLEDGE'
  | 'PORTFOLIO_INTELLIGENCE'
  | 'MARKET_SCOUT'
  | 'LISTING_EXTRACTION'
  | 'GEO_ENRICHMENT'

export type AgentRunStatus = 'QUEUED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'AWAITING_REVIEW'

export type TaskType =
  | 'REVIEW_SECTION'
  | 'UPLOAD_DOCUMENT'
  | 'VALIDATE_DATA'
  | 'AGENT_RUN'
  | 'FOLLOW_UP_BROKER'
  | 'ESCALATE'
  | 'APPROVE'
  | 'TECHNICAL_REVIEW'
  | 'LEGAL_REVIEW'
  | 'FINANCIAL_REVIEW'
  | 'COMPLIANCE_REVIEW'
  | 'CUSTOM'

export type TaskStatus = 'OPEN' | 'IN_PROGRESS' | 'BLOCKED' | 'COMPLETED' | 'CANCELLED' | 'ESCALATED'
export type TaskPriority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'

// ── Site summary (pipeline list view) ─────────────────────────────
export interface SiteSummary {
  id: string
  name: string
  slug: string
  status: SiteStatus
  stage: SiteStage
  siteType: SiteType | null
  city: string | null
  state: string | null
  targetItMW: number | null
  totalScore: number | null
  recommendation: SiteRecommendation | null
  completenessScore: number
  criticalRiskCount: number
  openTaskCount: number
  createdAt: string
  updatedAt: string
}

// ── Scorecard ────────────────────────────────────────────────────────────
export interface ScorecardData {
  id: string
  strategicFit: number | null
  powerExpandability: number | null
  coolingAiReadiness: number | null
  networkLatency: number | null
  resilienceSecurity: number | null
  complianceSovereignty: number | null
  operationalMaturity: number | null
  financialAttractiveness: number | null
  totalScore: number | null
  confidenceScore: number | null
  recommendation: SiteRecommendation | null
  rationale: string | null
  keyStrengths: string | null
  keyWeaknesses: string | null
  verifiedFieldCount: number
  totalFieldCount: number
  missingCriticalFields: string | null
  computedAt: string | null
}

// ── Risk flag ────────────────────────────────────────────────────────────
export interface RiskFlagData {
  id: string
  category: RiskCategory
  severity: RiskSeverity
  title: string
  description: string
  evidence: string | null
  recommendation: string | null
  isAutoGenerated: boolean
  isResolved: boolean
  resolvedAt: string | null
  createdAt: string
}

// ── Agent run ────────────────────────────────────────────────────────────
export interface AgentRunData {
  id: string
  agentType: AgentType
  status: AgentRunStatus
  summary: string | null
  error: string | null
  confidenceScore: number | null
  factsExtracted: number
  risksDetected: number
  startedAt: string | null
  completedAt: string | null
  durationMs: number | null
  createdAt: string
  triggeredBy: { name: string } | null
}

// ── Workflow task ────────────────────────────────────────────────────────
export interface WorkflowTaskData {
  id: string
  title: string
  description: string | null
  taskType: TaskType
  priority: TaskPriority
  status: TaskStatus
  dueDate: string | null
  completedAt: string | null
  owner: { id: string; name: string } | null
  createdAt: string
}

// ── Agent run output payload ─────────────────────────────────────────────
export interface AgentOutputPayload {
  agentType: AgentType
  siteId: string
  summary: string
  confidence: number
  extractedFacts: ExtractedFactPayload[]
  riskFlags: RiskFlagPayload[]
  recommendations: AgentRecommendationPayload[]
  missingCriticalFields: string[]
  notes?: string
}

export interface ExtractedFactPayload {
  fieldPath: string
  fieldLabel: string
  value: string
  confidence: number
  isInferred: boolean
  evidence?: string
}

export interface RiskFlagPayload {
  category: RiskCategory
  severity: RiskSeverity
  title: string
  description: string
  recommendation?: string
}

export interface AgentRecommendationPayload {
  category: string
  recommendation: string
  confidence: number
  evidence?: string
}

// ── Scoring input (flat representation for the engine) ────────────────────
export interface SiteScoringInput {
  // Power
  deliveredMW: number | null
  expandableMW: number | null
  feedCount: number | null
  hasFeedDiversity: boolean | null
  generatorCount: number | null
  generatorCapacityKwEach: number | null
  generatorAutonomyHours: number | null
  generatorRedundancy: string | null
  btmCapacityMW: number | null
  // UPS
  upsRuntimeMinutes: number | null
  upsRedundancyModel: string | null
  upsCapacityKw: number | null
  // Cooling
  coolingType: string | null
  isLiquidCoolingReady: boolean | null
  hasCdu: boolean | null
  hasImmersionCooling: boolean | null
  maxRackKwSupported: number | null
  pueAnnual: number | null
  pueTarget: number | null
  // Network
  carriersOnSite: number | null
  hasRouteDiversity: boolean | null
  hasDarkFiber: boolean | null
  hasMeetMeRoom: boolean | null
  aggregateBandwidthTbps: number | null
  ixProximityMiles: number | null
  cloudLatencyMs: number | null
  // Security
  hasMantraps: boolean | null
  hasBiometrics: boolean | null
  hasSocNoc: boolean | null
  hasCctvDataCenter: boolean | null
  hasCabinetLocks: boolean | null
  // Compliance
  hasSoc2: boolean | null
  hasIso27001: boolean | null
  hasCjis: boolean | null
  sovereignSuitable: boolean | null
  financialInfraSuitable: boolean | null
  digitalAssetSuitable: boolean | null
  uptimeTier: string | null
  // Ops
  gridReliabilityPercent: number | null
  yearBuilt: number | null
  hasTestSchedule: boolean | null
  // Financial
  ppaPricePerKwh: number | null
  hasPpa: boolean | null
  hasTaxAbatement: boolean | null
  totalProjectCostM: number | null
  targetIrrLevered: number | null
  // Site
  siteType: SiteType | null
  targetItMW: number | null
  maxExpandableMW: number | null
  jurisdiction: string | null
  ownershipStatus: string | null
  totalAcres: number | null
}

export interface ScoringResult {
  scores: {
    strategicFit: number
    powerExpandability: number
    coolingAiReadiness: number
    networkLatency: number
    resilienceSecurity: number
    complianceSovereignty: number
    operationalMaturity: number
    financialAttractiveness: number
  }
  totalScore: number
  confidenceScore: number
  recommendation: SiteRecommendation
  rationale: string
  redFlags: string[]
  missingCriticalFields: string[]
}

// ── API response types ────────────────────────────────────────────────────
export interface ApiResponse<T> {
  data?: T
  error?: string
  message?: string
}

export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  pageSize: number
  totalPages: number
}

// ── Dashboard KPI snapshot ────────────────────────────────────────────────
export interface DashboardKpis {
  activeSites: number
  approvedSites: number
  pipelineMW: number
  approvedMW: number
  avgScore: number
  avgCompleteness: number
  criticalRiskSites: number
  openTasks: number
  overdueTasks: number
  agentRunsToday: number
  pendingApprovals: number
}

// ── Notification ─────────────────────────────────────────────────────────
export type NotificationType =
  | 'TASK_ASSIGNED'
  | 'TASK_DUE'
  | 'TASK_OVERDUE'
  | 'AGENT_COMPLETE'
  | 'RISK_DETECTED'
  | 'APPROVAL_REQUIRED'
  | 'SITE_UPDATED'
  | 'DOCUMENT_UPLOADED'
  | 'SYSTEM'

export interface NotificationData {
  id: string
  title: string
  body: string | null
  type: NotificationType
  isRead: boolean
  actionUrl: string | null
  createdAt: string
  site: { id: string; name: string } | null
}
